//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HPetriSim.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_AUTHOR                      100
#define IDS_URL                         101
#define IDB_SPLASH                      102
#define IDS_MAILTO                      102
#define IDS_REGISTRY                    103
#define IDS_COPYRIGHT                   104
#define IDS_SOFTWARE                    105
#define IDS_LICENCE_URL                 106
#define IDS_LIC_URL                     106
#define IDD_PROPPAGE3                   111
#define IDS_PROPSHT_CAPTION1            112
#define ID_INDICATOR_STEPTIME           125
#define ID_INDICATOR_SIMSTATUS          126
#define ID_INDICATOR_SIMTIME            127
#define IDR_MAINFRAME                   128
#define IDR_HPSTYPE                     129
#define IDR_EDITBAR                     130
#define ID_INDICATOR_COUNT              131
#define ID_INDICATOR_MOUSEPOS           133
#define ID_INDICATOR_ZOOMSCALE          134
#define ID_SLIDER_SIMSPEED              136
#define IDR_SYMBAR                      137
#define IDR_SYM_VIEW                    139
#define ID_PAUSE_MODE                   140
#define IDR_SYM_OUTPUT_VIEW             141
#define ID_SPEED_MODE                   142
#define ID_VIEW_OUTPUTWND               142
#define IDS_CONVERT_OLDDOCVER           143
#define IDR_HPS_OUTPUT                  144
#define IDD_POSITION_DIALOG             146
#define IDR_MAINBAR                     151
#define IDS_ERROR_FILE_OPEN             152
#define IDD_SYMSTATE_VIEW               153
#define IDS_ERROR_INIT_NET              153
#define IDS_ERROR_MEMORY                154
#define IDS_ERROR_CONN_D                155
#define IDS_ERROR_CONN_A                156
#define IDB_EDITBAR                     157
#define IDS_ERROR_CONN_B                157
#define IDB_WRITELARGE                  157
#define IDS_ERROR_CONN_C                158
#define IDC_RECT                        169
#define IDS_LIMIT_TEXT                  182
#define IDS_ABOUT_TEXT                  183
#define IDS_MEM_TEXT                    184
#define IDS_EMAIL                       185
#define IDS_ABOUT_LIMIT                 186
#define IDB_BITMAP1                     187
#define IDB_SHAPEFORMAT_SMALL           187
#define IDR_POPUP_MDITABS               189
#define IDR_POPUP_DROP_MDITABS          190
#define IDR_WINDOWS_MENU                191
#define IDB_OBJECT_FORMAT               192
#define IDI_ICON1                       194
#define IDI_DISCONNECTED                194
#define IDB_BITMAP2                     195
#define IDB_LINESTYLE                   195
#define IDI_ICON2                       196
#define IDI_TIMER                       196
#define IDB_BITMAP3                     197
#define IDB_SHAPEFORMAT_LARGE           197
#define IDB_PROPERTIESSMALL             198
#define IDB_BITMAP4                     199
#define IDB_PROPERTIESLARGE             199
#define IDR_TOOLBAR1                    200
#define IDR_SYMBAR_256                  204
#define IDC_ZOOM_IN_CURSOR              208
#define IDC_ZOOM_OUT_CURSOR             209
#define IDB_WRITESMALL                  210
#define IDB_BUTTONS                     212
#define IDB_MAIN                        214
#define IDB_FILESMALL                   215
#define IDB_FILELARGE                   216
#define IDB_VIEWSMALL                   218
#define IDB_VIEWLARGE                   219
#define IDB_HOMESMALL                   220
#define IDB_HOMELARGE                   225
#define IDC_LINE                        227
#define IDC_ELLIPSE                     230
#define IDC_ROUND                       231
#define IDC_POLY                        233
#define IDC_TEXT                        234
#define IDC_POSITION                    235
#define IDC_TRANSITION                  236
#define IDC_CONNECTOR                   237
#define IDB_LINEWEIGHT                  240
#define IDB_FILLSTYLES                  242
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_RIBBON_ZOOM                 291
#define IDS_RIBBON_OUTPUTWND            292
#define IDS_RIBBON_PROPERTIESWND        293
#define IDS_RIBBON_ZOOM_NORM            294
#define IDS_RIBBON_ZOOM_IN              295
#define IDS_RIBBON_ZOOM_OUT             296
#define IDS_RIBBON_ZOOM_FULL            298
#define IDS_RIBBON_SHOWORHIDE           299
#define IDS_BUILD_TAB                   300
#define IDS_RIBBON_SHOWLABEL            300
#define IDS_DEBUG_TAB                   301
#define IDS_RIBBON_SHAPES               301
#define IDS_RIBBON_LINE                 302
#define IDS_RIBBON_RECT                 303
#define IDS_RIBBON_POLYGON              304
#define IDS_RIBBON_TEXT                 305
#define IDS_EDIT_MENU                   306
#define IDS_RIBBON_POSITION             306
#define IDS_RIBBON_TRANSITION           307
#define IDS_RIBBON_CONNECTOR            308
#define IDS_RIBBON_SELECT               309
#define IDS_RIBBON_EDIT                 310
#define IDS_RIBBON_DRAW                 311
#define IDS_RIBBON_DELETE               312
#define IDS_RIBBON_ELLIPSE              313
#define IDS_RIBBON_ROUNDRECT            314
#define IDS_RIBBON_OBJECTS              315
#define IDS_RIBBON_LINECOLOR            316
#define IDS_RIBBON_GRID                 317
#define IDS_RIBBON_SHOW_GRID            318
#define IDS_RIBBON_ALIGN_GRID           319
#define IDS_RIBBON_CAT_SIM              320
#define IDS_RIBBON_POSITION_TOKEN_NOW   321
#define IDS_RIBBON_POSITION_TOKEN_INITIAL 322
#define IDS_RIBBON_POSITION_TOKEN_CAPACITY 323
#define IDS_RIBBON_POSITION_TOKEN_COUNTER 324
#define IDS_RIBBON_FILLCOLOR            325
#define IDS_RIBBON_NOFILL               326
#define IDS_RIBBON_LINEWEIGHT           327
#define IDS_RIBBON_OBJECTSIZE           328
#define ID_SHAPE_FORMAT_CONTEXT_TAB     328
#define ID_OBJECT_FORMAT_CONTEXT_TAB    329
#define ID_WINDOWS_MENU                 330
#define ID_OBJECT_MOVEFORWARD           331
#define ID_OBJECT_MOVETOFRONT           332
#define ID_OBJECT_MOVEBACK              333
#define ID_OBJECT_MOVETOBACK            334
#define ID_CANCEL_EDIT                  335
#define ID_VIEW_FULLSCREEN              336
#define ID_STATUSBAR_SIMSTATUS          337
#define ID_STATUSBAR_MOUSEPOS           338
#define ID_UPDATE_PROPERTYS             471
#define ID_INDICATOR_STEPCOUNT          472
#define IDS_TOOLBAR_STANDARD            473
#define IDS_TOOLBAR_CUSTOMIZE           474
#define ID_OBJECT_PROPERTYS             474
#define IDS_TOOLBAR_EDIT                475
#define ID_VIEW_PROPERTIESWND           475
#define IDS_TOOLBAR_SIM                 476
#define ID_VIEW_CUSTOMIZE               476
#define IDS_OUTPUT_WND                  477
#define ID_WINDOW_MANAGER               477
#define IDS_PROPERTIES_WND              478
#define ID_ZOOM_FULL                    478
#define IDS_WINDOWS_MANAGER             479
#define ID_EDIT_DELETE                  480
#define ID_SHOW_GRID                    481
#define ID_ALING_GRID                   482
#define ID_GRID_SIZE                    483
#define ID_DOCUMENT_HEIGHT              484
#define ID_DOCUMENT_WIDTH               485
#define ID_DOCUMENT_COLOR               486
#define ID_FIRST_CUSTOM_PROPERTY        500
#define ID_POSITION_TOKEN_NOW           500
#define ID_POSITION_TOKEN_INITIAL       501
#define ID_POSITION_TOKEN_CAPACITY      502
#define ID_POSITION_TOKEN_COUNTER       503
#define ID_OBJECT_LINECOLOR             504
#define ID_OBJECT_FILLCOLOR             505
#define ID_OBJECT_LINEWEIGHT            506
#define ID_OBJECT_SIZE                  507
#define ID_OBJECT_FILLCOLOR2            508
#define ID_OBJECT_FILLSTYLE             509
#define ID_OBJECT_FONT_NAME             510
#define ID_OBJECT_FONT_SIZE             511
#define ID_OBJECT_FONT_COLOR            512
#define ID_TRANSITION_TIME_MODE         513
#define ID_TRANSITION_TIME_START        514
#define ID_TRANSITION_TIME_RANGE        515
#define ID_TRANSITION_TOKEN_COUNTER     516
#define ID_OBJECT_TEXT                  517
#define ID_OBJECT_X                     518
#define ID_OBJECT_Y                     519
#define ID_OBJECT_CX                    520
#define ID_OBJECT_CY                    521
#define ID_CONNECTOR_WEIGHT             522
#define ID_CONNECTOR_TYPE               523
#define ID_OBJECT_LINESTYLE             524
#define ID_OBJECT_NAME                  525
#define ID_LAST_CUSTOM_PROPERTY         525
#define ID_LASTPOS_CUSTOM_PROPERTY      599
#define ID_FIRST_BOOL_PROPERTY          600
#define ID_OBJECT_NOBORDER              601
#define ID_OBJECT_FONT_BOLD             602
#define ID_OBJECT_FONT_ITALIC           603
#define ID_OBJECT_FONT_UNDERLINE        604
#define ID_OBJECT_FONT_STRIKEOUT        605
#define ID_OBJECT_TEXT_AUTOSIZE         606
#define ID_OBJECT_TEXT_LEFT             607
#define ID_OBJECT_TEXT_CENTER           608
#define ID_OBJECT_TEXT_RIGHT            609
#define ID_OBJECT_TEXT_TOP              610
#define ID_OBJECT_TEXT_LINE_CENTER      611
#define ID_OBJECT_TEXT_BOTTOM           612
#define ID_OBJECT_FONT_SIZE_PLUS        613
#define ID_OBJECT_FONT_SIZE_MINUS       614
#define ID_OBJECT_CLOSEFIGURE           615
#define ID_SHOW_LABEL_01                616
#define ID_SHOW_LABEL_02                617
#define ID_LAST_BOOL_PROPERTY           617
#define ID_LASTPOS_BOOL_PROPERTY        699
#define ID_FIRST_COMMAND_PROPERTY       700
#define ID_LAST_COMMAND_PROPERTY        701
#define ID_LASTPOS_COMMAND_PROPERTY     799
#define ID_SIM_SPEED                    800
#define ID_FIRST_SIM_COMMAND            801
#define ID_SIM_RESET                    802
#define ID_SIM_ON                       803
#define ID_SIM_PAUSE                    804
#define ID_SIM_STEP                     805
#define ID_SIM_RUN                      806
#define ID_SIM_RUNFAST                  807
#define ID_SIM_STEP_LIMIT               808
#define ID_SIM_TIME_LIMIT               809
#define ID_LAST_SIM_COMMAND             809
#define ID_FIRST_ARRANGE                820
#define ID_ARRANGE_TOFRONT              820
#define ID_ARRANGE_UP                   821
#define ID_ARRANGE_DOWN                 822
#define ID_ARRANGE_TOBACK               823
#define ID_LAST_ARRANGE                 823
#define IDC_DELAY_TOKEN_RADIO           1023
#define IDC_RAND_TOKEN_RADIO            1024
#define IDC_START_TOKEN_RADIO           1026
#define IDC_RESTART_CHECK               1027
#define IDC_EDIT1                       1054
#define IDC_EDIT_MEM                    1054
#define IDC_EDIT2                       1055
#define IDC_EDIT_ABOUT                  1055
#define IDC_SLIDER_SPEED                1058
#define IDC_LIST_ENUM_DRIVES            1067
#define IDC_HYPERLINK                   1076
#define IDC_STATIC_SERIAL               1077
#define IDC_STATIC_NAME                 1078
#define IDC_STATIC_AUTHOR               1078
#define IDC_STATIC_NAME2                1079
#define IDC_STATIC_SOFTWARE             1079
#define IDC_STATIC_COPYRIGHT            1080
#define IDC_BUTTON_URL                  1081
#define IDC_BUTTON_URL2                 1082
#define IDC_BUTTON_MAILTO               1082
#define IDC_BUTTON_LIC_URL              1083
#define ID_STOP_MODE                    32785
#define ID_STEP_MODE                    32786
#define ID_SYM_MODE                     32787
#define ID_RUN_MODE                     32788
#define ID_SYM_PROPERTYS                32790
#define ID_ZOOM_IN                      32794
#define ID_VIEW_SYM_OUTPUT              32795
#define ID_ZOOM_NORM                    32797
#define ID_ZOOM_OUT                     32798
#define ID_ZOOM_PORT                    32799
#define ID_RECT_BORDERCOLOR             32800
#define ID_RECT_FILLCOLOR               32801
#define ID_CONTEXT_BORDERCOLOR          32802
#define ID_CONTEXT_POPUP                32823
#define ID_CONTEXT_PUSHBACK             32824
#define ID_GROUP                        32825
#define ID_UNGROUP                      32826
#define ID_EDITOR_EIGENSCHAFTEN         32827
#define ID_EDITOR_PROPERTIES            32828
#define ID_EDITOR_SHOWLABEL             32829
#define ID_SYM_SINGLESTEP               32830
#define ID_SYM_RUNNORMAL                32831
#define ID_SYM_RUNFAST                  32832
#define ID_SYM_STOP                     32833
#define ID_SYM_RESET                    32834
#define ID_SYM_INCREASESPEED            32835
#define ID_SYM_DECREASESPEED            32837
#define ID_STORE_SCREEN                 32862
#define ID_STORE_CLIENT                 32863
#define ID_ENABLE_WRITEOUTPUTFILE       32864
#define ID_FILE_EXPORT_NET              32865
#define ID_FILE_EXPORT_INTERCHANGE      32866
#define ID_FILE_IMPORT_INTERCHANGE      32867
#define ID_REMOVE_SELECTED              32868
#define ID_PAN_MODE                     32869
#define IDR_TOOLBAR                     32874
#define ID_TOOLBARSANDDOCKINGWINDOWS_   32875
#define ID_FIRST_MODE                   32880
#define ID_SELECT_TOOL                  32881
#define ID_RESIZE_MODE                  32883
#define ID_RECT_MODE                    32884
#define ID_LINE_MODE                    32885
#define ID_POSITION_MODE                32886
#define ID_TRANSITION_MODE              32887
#define ID_MULTI_LINE_MODE              32888
#define ID_CONNECTOR_MODE               32889
#define ID_TEXT_MODE                    32890
#define ID_POLYGON_MODE                 32891
#define ID_ELLIPSE_MODE                 32892
#define ID_ROUNDRECT_MODE               32893
#define ID_LAST_MODE                    32980
#define ID_MDI_NEW_HORZ_TAB_GROUP       32987
#define ID_MDI_NEW_VERT_GROUP           32988
#define ID_MDI_MOVE_TO_NEXT_GROUP       32989
#define ID_MDI_MOVE_TO_PREV_GROUP       32990
#define ID_DUMMY_ID                     32991

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        200
#define _APS_NEXT_COMMAND_VALUE         32995
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           339
#endif
#endif
